project_id = "ybqwwipwimnkonnebbys"

[functions.wapi-webhook]
verify_jwt = false

[functions.wapi-connect]
verify_jwt = true

[functions.wapi-send-message]
verify_jwt = true

[functions.ai-process-message]
verify_jwt = true

[functions.flow-engine]
verify_jwt = true

[functions.elevenlabs-stt]
verify_jwt = true

[functions.elevenlabs-tts]
verify_jwt = true

[functions.elevenlabs-agent-token]
verify_jwt = true

[functions.ai-playground]
verify_jwt = true

[functions.bitrix24-register]
verify_jwt = true

[functions.bitrix24-webhook]
verify_jwt = false

[functions.bitrix24-send]
verify_jwt = true

[functions.bitrix24-install]
verify_jwt = false
